import React from "react";
import Head from "next/head";
import { Container, Row, Col, Tabs, Tab } from "react-bootstrap";
import InfoIcon from "@mui/icons-material/Info";
import { Box, Typography } from "@mui/material";
import TableOne from "../../components/smart-money/TableOne";
import TableTwo from "../../components/smart-money/TableTwo";
import TableThree from "../../components/smart-money/TableThree";
import TableFour from "../../components/smart-money/TableFour";
import TableFive from "../../components/smart-money/TableFive";
import GraphOne from "../../components/smart-money/GraphOne";
export default function smartmoney() {
  return (
    <>
      <Head>
        <title>Smart Scan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          <Col xs={12}>
            <h3 className="pg_mn_ttl">
              smart scan
              <InfoIcon />
            </h3>
          </Col>
          <Col xs={12}>
            <Box className="smrtmn_infbx">
              <Typography>
                <InfoIcon />
                <Box>
                  Sometimes scammers send tokens to Smart Money Wallets in oder
                  to make it seems like there’ buying. Always doublecheck the
                  transaction is legitimate before making any investmenet
                  decisions.
                </Box>
              </Typography>
            </Box>
          </Col>
          <Col xs={12}>
            <Box className="TabBox">
              <Tabs
                defaultActiveKey="Dex_Trades"
                id="SmartMoneyTab"
                className="mb-5"
              >
                <Tab eventKey="Dex_Trades" title="dex trades">
                  <TableOne />
                </Tab>
                <Tab eventKey="Transactions" title="transactions">
                  <TableTwo />
                </Tab>
                <Tab eventKey="Token_Holdings" title="token holdings">
                  <Row>
                    <Col xs={12} className="mb-5">
                      <TableThree />
                    </Col>
                    <Col xs={12} lg={6} className="mb-4">
                      <GraphOne />
                    </Col>
                    <Col xs={12} lg={6} className="mb-4">
                      asd
                    </Col>
                    <Col xs={12} lg={6} className="mb-4">
                      <Box className="small_table_bx">
                        <TableFour />
                      </Box>
                    </Col>
                    <Col xs={12} lg={6} className="mb-4">
                      <Box className="small_table_bx">
                        <TableFive />
                      </Box>
                    </Col>
                  </Row>
                </Tab>
              </Tabs>
            </Box>
          </Col>
        </Row>
      </Container>
    </>
  );
}
